### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by manukumarbs**

### CODE REVIEW

**Comment by manojupadhya11** [comment]
test cases are failing because Sonarqube server is down

**Review by manojupadhya11 — COMMENTED** [review]
Code is fine checks are failing as Sonarquve server is down check with Devops Team member regarding Sonarqube

**Comment by manukumarbs** [comment]
> This Pull Request has conflicts, could you fix it @manukumarbs?

Sure will fix this issue before EOD

**Comment by manukumarbs** [comment]
@mergify refresh

**Comment by manukumarbs** [comment]
@mergify rebase

**Pull request merged**
